[workspace]
members = [
    "example/odd-api",
    "example/odd-impl",
    "example/even-api",
    "example/even-impl",
    "example/integrator",
    "dep-inj",
]

[patch.crates-io]
dep-inj = { path = "dep-inj" }