[package]
name = "even-impl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
even-api = { path = "../even-api" }
the-world = { path = "../the-world"}